################# Español language ################
[es]
languageName = "Español"
languageCode = "es-ES"
contentDir = "content/spanish"
weight = 3

################ French language ##################
[gl]
languageName = "Galego"
languageCode = "gl-GL"
contentDir = "content/galego"
weight = 2

################# English language ################
[en]
languageName = "English"
languageCode = "en-US"
contentDir = "content/english"
weight = 1
