[[main]]
name = "Home"
url = ""
identifier = "nav-home"
weight = 1

[[main]]
name = "Technology"
url = "service/"
weight = 2

[[main]]
name = "Products"
identifier = "products"
weight = 3

  [[main]]
  parent = "products"
  name = "Kosoku"
  url = "kosoku/"
  weight = 1

  [[main]]
  parent = "products"
  name = "Quko Live"
  url = "quko_live/"
  weight = 2

  [[main]]
  parent = "products"
  name = "Quko Cloud"
  url = "quko_cloud/"
  weight = 3

[[main]]
name = "More"
identifier = "more"
weight = 4

  [[main]]
  parent = "more"
  name = "About"
  url = "about/"
  weight = 1

  [[main]]
  parent = "more"
  name = "Blog"
  url = "blog/"
  weight = 2

  [[main]]
  parent = "more"
  name = "FAQ"
  url = "faq/"
  weight = 3

  [[main]]
  parent = "more"
  name = "Contact"
  url = "contact/"
  weight = 4

[[main]]
name = "Access Cloud"
url = "https://cloud.quko.es/"
identifier = "nav-cloud"
weight = 6

[[main]]
name = "Request a demo"
url = "contact/"
identifier = "nav-cta"
weight = 7

[[footer]]
name = "Products"
url = "kosoku/"
weight = 1
[[footer]]
name = "Technology"
url = "service/"
weight = 2
[[footer]]
name = "About"
url = "about/"
weight = 3
[[footer]]
name = "FAQ"
url = "faq/"
weight = 4
[[footer]]
name = "Privacy"
url = "privacy/"
weight = 5
[[footer]]
name = "Legal notice"
url = "legal_notice/"
weight = 6
