[[main]]
name = "Inicio"
url = ""
identifier = "nav-home"
weight = 1
[[main]]
name = "Tecnoloxía"
url = "service/"
weight = 2

[[main]]
name = "Produtos"
identifier = "products"
weight = 3
  [[main]]
  parent = "products"
  name = "Kosoku"
  url = "kosoku/"
  weight = 1
  [[main]]
  parent = "products"
  name = "Quko Live"
  url = "quko_live/"
  weight = 2
  [[main]]
  parent = "products"
  name = "Quko Cloud"
  url = "quko_cloud/"
  weight = 3
[[main]]
name = "Máis"
identifier = "more"
weight = 4
  [[main]]
  parent = "more"
  name = "Prezos"
  url = "pricing/"
  weight = 1

  [[main]]
  parent = "more"
  name = "Premios por resultados"
  url = "results_sponsorship/"
  weight = 2

  [[main]]
  parent = "more"
  name = "Recursos"
  url = "resources/"
  weight = 3

  [[main]]
  parent = "more"
  name = "Sobre QUKO"
  url = "about/"
  weight = 4
  [[main]]
  parent = "more"
  name = "Blog"
  url = "blog/"
  weight = 5
  [[main]]
  parent = "more"
  name = "Preguntas frecuentes"
  url = "faq/"
  weight = 6
  [[main]]
  parent = "more"
  name = "Contacto"
  url = "contact/"
  weight = 7
[[main]]
name = "Tenda"
url = "shop/"
identifier = "nav-shop"
weight = 5

[[main]]
name = "Acceder a Cloud"
url = "https://cloud.quko.es/"
identifier = "nav-cloud"
weight = 6
[[main]]
name = "Solicitar demo"
url = "contact/"
identifier = "nav-cta"
weight = 7
[[footer]]
name = "Produtos"
url = "kosoku/"
weight = 1
[footer.params]
group = "explore"
[[footer]]
name = "Tecnoloxía"
url = "service/"
weight = 2
[footer.params]
group = "explore"
[[footer]]
name = "Sobre QUKO"
url = "about/"
weight = 3
[footer.params]
group = "explore"
[[footer]]
name = "Preguntas frecuentes"
url = "faq/"
weight = 4
[footer.params]
group = "explore"
[[footer]]
name = "Premios por resultados"
url = "results_sponsorship/"
weight = 5
[footer.params]
group = "explore"
[[footer]]
name = "Privacidade"
url = "privacy/"
weight = 5
[footer.params]
group = "legal"
[[footer]]
name = "Privacidade Paddle Results"
url = "privacy_paddle_results/"
weight = 6
[footer.params]
group = "legal"
[[footer]]
name = "Aviso legal"
url = "legal_notice/"
weight = 7
[footer.params]
group = "legal"
[[footer]]
name = "Condicións de venda"
url = "sales_terms/"
weight = 8
[footer.params]
group = "legal"
[[footer]]
name = "Guía de marca"
url = "brand/"
weight = 9
[footer.params]
group = "developers"
[[footer]]
name = "Programa de partners"
url = "partners/"
weight = 10
[footer.params]
group = "developers"

[[footer]]
name = "APIs"
url = "apis/"
weight = 11
[footer.params]
group = "developers"
