############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = ""
weight = 1

[[main]]
name = "About"
url = "about/"
weight = 2

[[main]]
name = "Blog"
url = "blog/"
weight = 4

[[main]]
weight = 5
name = "Products"
hasChildren = true

  [[main]]
  parent = "Products"
  name = "Kosoku"
  url = "kosoku/"
  weight = 1

  [[main]]
  parent = "Products"
  name = "Quko Cloud"
  url = "quko_cloud/"
  weight = 2

  [[main]]
  parent = "Products"
  name = "Quko Live"
  url = "quko_live/"
  weight = 3




[[main]]
weight = 7
name = "More"
hasChildren = true

#  [[main]]
#  parent = "More"
#  name = "Service"
#  url = "service/"
#  weight = 1


  [[main]]
  parent = "More"
  name = "Services"
  url = "service/"
  weight = 1

  #[[main]]
  #parent = "More"
  #name = "Pricing"
  #url = "pricing/"
  #weight = 2

  [[main]]
  parent = "More"
  name = "Newsletter"
  url = "newsletter/"
  weight = 4

  [[main]]
  parent = "More"
  name = "FAQ"
  url = "faq/"
  weight = 3
  
  [[main]]
  parent = "More"
  name = "Contact"
  url = "contact/"
  weight = 4

[[main]]
name = "Access QUKO Cloud"
url = "https://app.quko.es/"
weight = 8


# footer menu

[[footer]]
name = "Home"
url = ""
weight = 1

[[footer]]
name = "About"
url = "about/"
weight = 2

#[[footer]]
#name = "Project"
#url = "project/"
#weight = 3

#[[footer]]
#name = "Pricing"
#url = "pricing/"
#weight = 5

[[footer]]
name = "FAQ"
url = "faq/"
weight = 6

[[footer]]
name = "Contact"
url = "contact/"
weight = 7