[[main]]
name = "Inicio"
url = ""
weight = 1
[[main]]
name = "Tecnoloxía"
url = "service/"
weight = 2

[[main]]
name = "Produtos"
identifier = "products"
weight = 3
  [[main]]
  parent = "products"
  name = "Kosoku"
  url = "kosoku/"
  weight = 1
  [[main]]
  parent = "products"
  name = "Quko Live"
  url = "quko_live/"
  weight = 2
  [[main]]
  parent = "products"
  name = "Quko Cloud"
  url = "quko_cloud/"
  weight = 3
[[main]]
name = "Máis"
identifier = "more"
weight = 4
  [[main]]
  parent = "more"
  name = "Sobre QUKO"
  url = "about/"
  weight = 1
  [[main]]
  parent = "more"
  name = "Blog"
  url = "blog/"
  weight = 2
  [[main]]
  parent = "more"
  name = "Preguntas frecuentes"
  url = "faq/"
  weight = 3
[[main]]
name = "Acceder a Cloud"
url = "https://cloud.quko.es/"
identifier = "nav-cloud"
weight = 6
[[main]]
name = "Solicitar demo"
url = "contact/"
identifier = "nav-cta"
weight = 7
[[footer]]
name = "Produtos"
url = "kosoku/"
weight = 1
[[footer]]
name = "Tecnoloxía"
url = "service/"
weight = 2
[[footer]]
name = "Sobre QUKO"
url = "about/"
weight = 3
[[footer]]
name = "Preguntas frecuentes"
url = "faq/"
weight = 4
[[footer]]
name = "Privacidade"
url = "privacy/"
weight = 5
[[footer]]
name = "Aviso legal"
url = "legal_notice/"
weight = 6
